config/routes.rb
Rails.application.routes.draw do
  get 'todolists/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'top' => 'homes#top'
  post 'todolists' => 'todolists#create'
  get 'todolists' => 'todolists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
		
	end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def new
  	@list = List.new
  end

  def index
  	@lists = List.all
  end

  def create
  	list = List.new(list_params)
  	list.save
  	redirect_to '/top'
  end

  private
  def list_params
  	params.require(:list).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/homes/top.html.erb
<h1>ここはトップページです。</h1>
<%= link_to todolists_path do %>
  投稿一覧
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolists/index.html.erb
<h1>投稿一覧</h1>
<%= @lists.each do |list|%>
	<p>タイトル</p>
	<span><%= list.title %></span>
<% end %>

app/views/todolists/new.html.erb
<h1>Todolists#new</h1>
<p>Find me in app/views/todolists/new.html.erb</p>

<%= form_for(@list, url: '/todolists') do |f| %>
	<h4>タイトル</h4>
	<%= f.text_field :title %>
	<h4>本文</h4>
	<%= f.text_area :body %>
	<%= f.submit '投稿'%>
<% end %>